"""Jinja2-based template rendering engine.

Loads templates from two locations (in priority order):
  1. <project>/.testgen/templates/  (user overrides)
  2. testgen/templates/             (built-in defaults)

Templates receive a context dict built by ContextBuilder and render
Java source files.  The engine is stateless — safe to reuse across calls.
"""

from __future__ import annotations

import logging
from pathlib import Path
from typing import Any

import jinja2

logger = logging.getLogger(__name__)

# Package-level templates directory
_BUILTIN_TEMPLATES = Path(__file__).resolve().parent.parent / "templates"

GENERATED_HEADER = (
    "// ──────────────────────────────────────────────────────────────\n"
    "// AUTO-GENERATED by testgen — do not edit.\n"
    "// Re-run the framework to regenerate.\n"
    "// ──────────────────────────────────────────────────────────────"
)


class TemplateEngine:
    """Renders Jinja2 templates with project-specific context."""

    def __init__(self, project_path: str | Path):
        user_templates = Path(project_path) / ".testgen" / "templates"
        search_paths: list[str] = []
        if user_templates.is_dir():
            search_paths.append(str(user_templates))
        search_paths.append(str(_BUILTIN_TEMPLATES))

        self._env = jinja2.Environment(
            loader=jinja2.FileSystemLoader(search_paths),
            keep_trailing_newline=True,
            trim_blocks=True,
            lstrip_blocks=True,
            undefined=jinja2.StrictUndefined,
        )
        # Register custom filters
        self._env.filters["camel_var"] = _camel_var
        self._env.filters["simple_type"] = _simple_type
        self._env.globals["header"] = GENERATED_HEADER

    def render(self, template_name: str, context: dict[str, Any]) -> str:
        """Render a template with the given context dict."""
        try:
            template = self._env.get_template(template_name)
            return template.render(context)
        except jinja2.TemplateNotFound:
            logger.error("Template not found: %s", template_name)
            raise
        except jinja2.TemplateError as exc:
            logger.error("Template error in %s: %s", template_name, exc)
            raise

    def has_template(self, template_name: str) -> bool:
        try:
            self._env.get_template(template_name)
            return True
        except jinja2.TemplateNotFound:
            return False


def _camel_var(class_name: str) -> str:
    """'MyService' → 'myService' (instance variable name)."""
    if not class_name:
        return class_name
    return class_name[0].lower() + class_name[1:]


def _simple_type(full_type: str) -> str:
    """'com.foo.Bar' → 'Bar', 'List<Foo>' → 'Foo'."""
    from ..models import simple_type_name
    return simple_type_name(full_type)
