package ca.optaintel.ws.optasingleservice._2_0;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

import ca.optaintel.ws.optasingleservice._2.OSSRequestType;
import ca.optaintel.ws.optasingleservice._2.OSSResponseType;
import ca.optaintel.ws.optasingleservice._2.ObjectFactory;

/**
 * This class was generated by Apache CXF 3.0.2
 * 2025-08-27T14:32:32.284-04:00
 * Generated source version: 3.0.2
 * 
 */
@WebService(targetNamespace = "http://www.optaintel.ca/ws/OptaSingleService/1.0", name = "OptaSingleServicePort")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface OptaSingleServicePort {

    @WebMethod
    @WebResult(name = "OSSResponse", targetNamespace = "http://www.optaintel.ca/ws/OptaSingleService/1.0", partName = "Response")
    public OSSResponseType call(
        @WebParam(partName = "Request", name = "OSSRequest", targetNamespace = "http://www.optaintel.ca/ws/OptaSingleService/1.0")
        OSSRequestType request
    );
}
