--------------------------------------------------------
--  File created - Monday-Oct-15-2018  
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table OssFUSService TRANSACTIONS
--------------------------------------------------------

  CREATE TABLE "BDQWDAPI"."CL_FUS_TRANS_LOG" 
   (	
	"TRANSACTION_ID" VARCHAR2(48 BYTE), 
	"APPLICATION" VARCHAR2(20 BYTE), 
	"URL" VARCHAR2(200 BYTE), 
	"TRANSACTION_TIME" TIMESTAMP (6), 
	"CLIENT_ID" VARCHAR2(30 BYTE),
	"CLIENT_NAME" VARCHAR2(30 BYTE), 
	"CLIENT_GUID" VARCHAR2(30 BYTE), 
	"DWELLING_FIRE_PROTECTION" VARCHAR2(200 BYTE),
	"STREET_NAME" VARCHAR2(200 BYTE),
	"POSTAL_CODE" VARCHAR2(8 BYTE), 
	"MUNICIPALITY" VARCHAR2(50 BYTE), 
	"PROVINCE" VARCHAR2(10 BYTE),
	"REQ_PAYLOAD" CLOB, 
	"RES_PAYLOAD" CLOB, 
	"STATUS" VARCHAR2(10 BYTE), 
	"ERROR_CODE" VARCHAR2(10 BYTE),
	"ERROR_MESSAGE" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BDQWDAPI_LOG"   NO INMEMORY 
  LOB ("REQ_PAYLOAD") STORE AS SECUREFILE (
  TABLESPACE "BDQWDAPI_LOG" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE NOLOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;

   COMMENT ON COLUMN "BDQWDAPI"."CL_FUS_TRANS_LOG"."TRANSACTION_ID" IS 'Unique sequence for the requests';
   COMMENT ON COLUMN "BDQWDAPI"."CL_FUS_TRANS_LOG"."APPLICATION" IS 'The Source application (OssFUSService)';
   COMMENT ON COLUMN "BDQWDAPI"."CL_FUS_TRANS_LOG"."URL" IS 'The URL from/to request received/sent';
   COMMENT ON COLUMN "BDQWDAPI"."CL_FUS_TRANS_LOG"."TRANSACTION_TIME" IS 'Timestamp';
   COMMENT ON COLUMN "BDQWDAPI"."CL_FUS_TRANS_LOG"."CLIENT_ID" IS 'Client ID Value';
   COMMENT ON COLUMN "BDQWDAPI"."CL_FUS_TRANS_LOG"."CLIENT_NAME" IS 'Client Name Value';
   COMMENT ON COLUMN "BDQWDAPI"."CL_FUS_TRANS_LOG"."CLIENT_GUID" IS 'Client GUID Value';
   COMMENT ON COLUMN "BDQWDAPI"."CL_FUS_TRANS_LOG"."DWELLING_FIRE_PROTECTION" IS 'Dwelling Fire Protection Value';
   COMMENT ON COLUMN "BDQWDAPI"."CL_FUS_TRANS_LOG"."REQ_PAYLOAD" IS 'Request Message content';
   COMMENT ON COLUMN "BDQWDAPI"."CL_FUS_TRANS_LOG"."RES_PAYLOAD" IS 'Response Message content';
   COMMENT ON COLUMN "BDQWDAPI"."CL_FUS_TRANS_LOG"."STATUS" IS 'Success or error code from fuse(FXXXX)';
   COMMENT ON COLUMN "BDQWDAPI"."CL_FUS_TRANS_LOG"."ERROR_CODE" IS 'Erro Code Value';
   COMMENT ON COLUMN "BDQWDAPI"."CL_FUS_TRANS_LOG"."ERROR_MESSAGE" IS 'Error Message Value';
   COMMENT ON COLUMN "BDQWDAPI"."CL_FUS_TRANS_LOG"."STREET_NAME" IS 'Street Name Value';
   COMMENT ON COLUMN "BDQWDAPI"."CL_FUS_TRANS_LOG"."POSTAL_CODE" IS 'Postal Code Value';
   COMMENT ON COLUMN "BDQWDAPI"."CL_FUS_TRANS_LOG"."MUNICIPALITY" IS 'Municipality Value';
   COMMENT ON COLUMN "BDQWDAPI"."CL_FUS_TRANS_LOG"."PROVINCE" IS 'Province Field Value';

   -------------------------------------------------------------
   ------------Table Altering for Prod Issue-------------------
   ALTER TABLE BDQWDAPI.CL_FUS_TRANS_LOG MODIFY (CLIENT_ID varchar2(50), CLIENT_GUID varchar2(50), CLIENT_NAME varchar2(50));
   -------------------------------------------------------
   --------------------------------------------------------------
   
   