package com.aviva.ca.esb.cl.opta.fus.model;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "SOAPServiceException", targetNamespace = "http://api.esb.ca.aviva.com/v1.0/")
public class SOAPServiceException
    extends Exception
{

    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	/**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
	private DetailException soapServiceException;
	public SOAPServiceException() {
        super();
    }
    
    public SOAPServiceException(String message) {
        super(message);
    }
    
    public SOAPServiceException(String message, Throwable cause) {
        super(message, cause);
    }

    public SOAPServiceException(String message, DetailException soapServiceException) {
        super(message);
        this.soapServiceException = soapServiceException;
    }

    public SOAPServiceException(String message, DetailException soapServiceException, Throwable cause) {
        super(message, cause);
        this.soapServiceException = soapServiceException;
    }

    public DetailException getFaultInfo() {
        return this.soapServiceException;
    }
   

}