package ca.optaintel.ws.optasingleservice._2_0;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * Opta Single Service
 *         
 *
 * This class was generated by Apache CXF 3.0.2
 * 2025-08-27T14:32:32.316-04:00
 * Generated source version: 3.0.2
 * 
 */
@WebServiceClient(name = "OptaSingleService", 
                  wsdlLocation = "classpath:wsdl/OSS.wsdl",
                  targetNamespace = "http://www.optaintel.ca/ws/OptaSingleService/1.0") 
public class OptaSingleService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.optaintel.ca/ws/OptaSingleService/1.0", "OptaSingleService");
    public final static QName OptaSingleServicePort = new QName("http://www.optaintel.ca/ws/OptaSingleService/1.0", "OptaSingleServicePort");
    static {
        URL url = null;
        try {
            url = new URL("file:classpath:wsdl/OSS.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(OptaSingleService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "classpath:wsdl/OSS.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public OptaSingleService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public OptaSingleService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public OptaSingleService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns OptaSingleServicePort
     */
    @WebEndpoint(name = "OptaSingleServicePort")
    public OptaSingleServicePort getOptaSingleServicePort() {
        return super.getPort(OptaSingleServicePort, OptaSingleServicePort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns OptaSingleServicePort
     */
    @WebEndpoint(name = "OptaSingleServicePort")
    public OptaSingleServicePort getOptaSingleServicePort(WebServiceFeature... features) {
        return super.getPort(OptaSingleServicePort, OptaSingleServicePort.class, features);
    }

}
